### ISSUE TITLE
Get intersections

### ISSUE THREAD

**Issue by tiste** [yvecai/opensnowmap.org#17]
Hey,

First, thank you so much for the amazing job you did. It's really helpful, and well done.
Thanks again.

I'm just looking at the code to get intersections for a given slope. Do you have any idea? It's the first time I work with openstreetmap data.

I aim to build a graph for "La Plagne" for instance, in which I could retrieve all the possibility/destinations for a given slope.

**Comment by yvecai** [comment]
That's a general OSM question.
You should look for routing tools working with OSM data. Opensnowmap can help you in providing the pistes data worldwide at http://www.opensnowmap.org/download/planet_pistes.osm.gz, and to ask your question on https://help.openstreetmap.org/ .
:-)
