### ISSUE TITLE
Abandoned pistes

### ISSUE THREAD

**Issue by solitone** [yvecai/opensnowmap.org#19]
Pistes that the resort's operator no longer maintains are tagged as **piste:abandoned=yes**. OpenSnowMap doesn't differentiate such abandoned pistes from standard ones, and this can be misleading for a map user. Would it be possible to render them differently (e.g. dashed)?

**Comment by yvecai** [comment]
That make sense. Probably I would not render them at all.

**Comment by solitone** [comment]
Yes, probably not showing them is the best thing. They might be showed only in sort of special purpose historic maps.
