### ISSUE TITLE
render only lifts in operation

### ISSUE THREAD

**Issue by MichalPP** [yvecai/opensnowmap.org#20]
rendering skilifts/pistes which are operational right now would be a nice feature. this would require quering websites of ski resorts for information about which skilifts are in operation and which pistes have snow. apart from other problems (eg timezones, hw requirements,...) I do not know of a standard API which ski resorts use.

Is there a standard API/export which is published by ski resorts and describes current state of pistes/skilifts?

**Comment by yvecai** [comment]
I don't know, I think there is probably several APIs, and probably closed.
