### ISSUE TITLE
ski routing integration

### ISSUE THREAD

**Issue by MichalPP** [yvecai/opensnowmap.org#21]
I publish routing for downhill skiing ([example](https://www.freemap.sk/?map=13/46.602702/7.955303&layers=O&tool=route-planner&points=46.588596/7.962170,46.607823/7.944660,46.621975/7.991697&transport=ski) - worldwide). [source code](https://github.com/FreemapSlovakia/freemap-routing/blob/master/master-ski.lua). it is run by OSRM with standard OSRM api, [here is an example](http://www.liedman.net/openlayers-routing-machine/) of routing integration into openlayers.

is it possible to integrate into snowmap?

**Comment by yvecai** [comment]
Congratulation, this works well.
It's a good idea to replace pyroute by OSRM, however it would require some modification of the 'piste API' too, both js + python CGI.
I'd say that for the moment, pyroute is good enough for Opensnowmap, but as yours shows quite well,  there is room for better ski routing engines :-)

**Comment by MichalPP** [comment]
in the routing api, I can also remove some piste (eg remove advanced, or remove ski lifts and leave only gondolas).

disadvantage of OSRM is, that it's impossible to make custom modifications of weights (user A cannot configure that he/she prefers intermediate pistes and user B beginners; user B can exclude non-beginners pistes but that will avoid all non-beginners pistes even if they are only 10m long). also, it's impossible to make offline mobile application.

advantage is that apart of 300mb of consumed RAM, it makes no load on my server.

**Comment by yvecai** [comment]
A first implementation with PGRouting is now operational from https://github.com/yvecai/opensnowmap.org/commit/60a91b91a4a79d302dad534458468a83d2227220
