### ISSUE TITLE
Question: What's the difference between dev and www folder

### ISSUE THREAD

**Issue by eMerzh** [yvecai/opensnowmap.org#23]
Hi, 

i'm not sure i understand the way the code is organised, the distinction between www and dev folder.
Is this some kind of version distinction (like in good old svn days?)

where should we make changes? both?

**Comment by eMerzh** [comment]
bonus question :-)  is there some way to run the app in local ? (i served the htmls but can't get the requests, tiles, .... working)

**Comment by yvecai** [comment]
Hello, dev folder is somtimes available from beta.opensnomwap.org and I use it for some live tests before deploying the changes on www.
Should certainly be a branch, but hey, it's not as if there is so many people working on this repo ;-)
