### ISSUE TITLE
Compute direction of Chairlifts icons

### ISSUE THREAD

**Issue by ldmpub** [yvecai/opensnowmap.org#24]
Hi,

Could you please tell me why "chairlift icons" are not always in the good direction on OpenSnowMap?

For instance below icons are reversed:
![Chairlifts with wrong direction icons](https://user-images.githubusercontent.com/1452146/68157366-cbe72a80-ff4d-11e9-9613-e57aabf1262b.jpg)

It's very easy to know, even automatically, what is bottom and what is the top of a slope with contour lines.

What is the rule yet for these icons? Is it possible to change this very strange behaviour by dev or do users need to edit manually each chairlift?

**Comment by yvecai** [comment]
It's because I'm a cross country skier and never take lifts :)
More seriously, you're right in the map style I don't look for the actual direction of the lift.
I do however pay attention to the way the icon is rendered, so that the people on the lifts icon have their head above their skis. Otherwise it looks *really* strange. 
Maybe I could take care of the lift direction too in using to icons, one left one right, I never tried. Do you want to give it a go? This is here:
https://github.com/yvecai/mapnik-opensnowmap.org/blob/master/pistes-carto/project.yml#L932

I guess most lifts should be mapped to their normal direction (uphill), or with a oneway tag of some kind. 
The contours are in another database, and while technically feasible, that would be a hard work  to keep the OSM data up-to-date along with elevation, non speaking of the DEM accuracy. I'd better rely to mapping for this. 
Yves 
(Actually I took a lift once with my skatings. My thigs are still hurting from the way down)

**Comment by ldmpub** [comment]
Hi Yves,

Maybe you're a cross country skier but many thanks for this great tool usefull for all "alpine skiers" like me ;-).

I'm guessing that you are french ... du coup la suite en français parce que j'avoue avoir du mal avec l'anglais (aussi bien pour les sujets techniques que pour comprendre vos blagues !).

Oui je suis partant pour un test de direction des remontées mécaniques. Une simple flèche pouvant très bien faire l'affaire même si cette représentation est plus éloignée de ce à quoi les skieurs sont habitués (cf les plans de pistes réalisés par les stations de ski).

Quant au DEM (digital elevation model) ... je ne maitrise absolument pas le sujet mais je comprend qu'il y a des contraintes de faisabilité technique comme les altitudes qui sont dans une autre base de données.

Je m'en remet à vous puisque vous avez semble t'il bien compris le "sens" de ma remarque.

A suivre donc...

**Comment by ldmpub** [comment]
Hi,

Any news about this request?

Thanks,

**Comment by ldmpub** [comment]
Hello,

Can I expect any change on this request before the beginning of the ski season?

Waiting for your answer, thanks,

**Comment by yvecai** [comment]
Hello Nam,
Opensnowmap comes with hillshade and contours, I guess people are able to guess the way up: its not really a bug.
As said, please have yourself a try taking care of the way direction in the style, that's why open-source project are made for.
You can refer to this issue here https://github.com/yvecai/mapnik-opensnowmap.org

**Comment by ldmpub** [comment]
Hi,

Thanks for your reply.

I agree it's not a bug but more an improvement to help users read the map more easily.

Unfortunately I have no development skills so I can not contribute to this open source project by writing code, except if you think it's very simple and you can help me along all steps.

**Comment by yvecai** [comment]
Closed in https://github.com/yvecai/mapnik-opensnowmap.org/commit/554a4a28cee72c67cda1adce4168009edac87be4

**Comment by ldmpub** [comment]
Thanks 👍🍾.

I'm egger to see it working on the web map ... (I again noticed this little "glich" yesterday).

**Comment by ldmpub** [comment]
Hi @yvecai,

After some tests, this new feature behave quite strangely 🧙‍♀️ in the 2 below situations ...

1. **All chairlift icons are not always the same along chairlift line** (and I have checked: the below chairlift does no go up 📈 then down 📉 😛):
![Strange](https://user-images.githubusercontent.com/1452146/150648405-a85cd806-e70c-46c1-8fd4-cab1cf12c508.jpg)


2. **The "chairlift direction" changes depending on "map zoom level"**:
2.1 Large zoom => wrong directions
![Mauvais sens 2](https://user-images.githubusercontent.com/1452146/150648560-49cdcae3-cb86-4507-b46b-667b5395120c.jpg)
2.1 Zoomed ++ => directions are correct
![Sens OK](https://user-images.githubusercontent.com/1452146/150648556-790fbee6-eba5-4689-8784-3e3b4adf19be.jpg)

**Do you think you can improve theses points?**


My 2 cents (sorry if it's not applicable ... I'not a developper 😕):
- for point 1: compute only 1 direction and apply it to all chairlift line (direction should be based on start and end chairlift altitude)
- for point 2: don't display any icon if zoom level is not enough to computed directions with accuracy.

**Comment by yvecai** [comment]
I strongly suspect a cache issue: tile rendering doesn't happened instantly.
Try to refresh your cache (shift+ctrl+r) then visit again the same areas.

**Comment by ldmpub** [comment]
Thanks for your quick reply 👍.

Refreshing the cache do no change the behavior.
Unfortunately it looks like it's not a cache issue, for instance I can reproduce the 2 "bugs" above easily in incognito mode 🤦‍♂️.

Note: I have guessed that the changes are already available online at [OpenSnowMap](http://www.opensnowmap.org/#map=14/6.013/45.247&b=snowmap&m=false&h=false).

**Comment by yvecai** [comment]
What we still see is the old tiles in case of 'grand cerf'. Look at the baby lift a bit north, you see a new tile left and an old tile right with the drag-lift icon cut at the tile edge. 
There is the browser cache but also the cache server-side. 
Tiles are render on-demand, unless they are available in the server cache. If the rendering is slow, the server still prefer to give you an old tile while rendering the new one.
There is an expiry mechanism if the underlying data has changed, and after a couple of days (depends on the zoom level).
I don't plan to force expire all tiles in the middle of the winter, so you'll have to wait that all tiles are visited before those glitch disappear.

**Comment by ldmpub** [comment]
@yvecai many thanks for your clear explanations 👏.

If reported "bugs" are linked to a server-side cache issue on tiles ... I have no problem to wait a couple of more days (all the more I see that my initial improvement request is from more than 2 years ago ... 😊).

Thanks again for your great job 👍
_(note: I have an other "very little" improvement to request)_

**Comment by yvecai** [comment]
You're welcome!
Just in case, lift directions are computed in the direction of the OSM way, not taking account altitude. That won't likely ever change 😁

**Comment by ldmpub** [comment]
It's perfect ... I did not know directions were available properties of chairlifts and stored in OSM structure, that's nice⭐.

New 'little' improvement requested here : 
* https://github.com/yvecai/opensnowmap.org/issues/31
