### ISSUE TITLE
CORS requests fail

### ISSUE THREAD

**Issue by rugk** [yvecai/opensnowmap.org#26]
The tiles are not loading in my case:
![cors](https://user-images.githubusercontent.com/11966684/78364223-6612d380-75bd-11ea-9468-eb04c7415a83.png)

https://developer.mozilla.org/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

Firefox 74

**Comment by yvecai** [comment]
Something special in your firefox?
Http or https?

**Comment by rugk** [comment]
Redirects to HTTPS. Not that many special things, several ad blockers etc.

**Comment by yvecai** [comment]
Sorry, there was a problem with the ssl certificate. This should be fixed now.
