### ISSUE TITLE
base_snow_map usage

### ISSUE THREAD

**Issue by berkantay** [yvecai/opensnowmap.org#27]
I am currently using ur pistes link https://tiles.opensnowmap.org/pistes/{z}/{x}/{y}.png however I wish to show map as your website. which is https://tiles.opensnowmap.org/base_snow_map/{z}/{x}/{y}.png. However I get acces denied image. How can I use base_snow_map?
cheers

**Comment by yvecai** [comment]
Hi, I have to limit the use of the base map to spare the server resources.
Can you please send me more information by email about the use intended to see if it is reasonable enough?

**Comment by berkantay** [comment]
Currently I am developing a mobile application for skiers and snowboarders
that shows weather and snow data from several API. I also aim to show their
current location on the pistes and share lift map. During my research on
internet I saw opensnowmap.org and I really liked it.
Cheers.

yvecai <notifications@github.com>, 12 May 2020 Sal, 21:41 tarihinde şunu
yazdı:
