### ISSUE TITLE
OSM data are offset

### ISSUE THREAD

**Issue by MaelREBOUX** [yvecai/opensnowmap.org#35]
Hello.

I'm really impressed by your work. What you are doing is really great.

I used your OSM data last day and I saw that there are offset as you can see below :

![image](https://user-images.githubusercontent.com/6370443/152703203-fd3a850c-96a0-49a9-b59f-e3565f000fb9.png)

Tested under JOSM and QGIS.

**Comment by yvecai** [comment]
Strange, can you point me to the file you used? 

Le 6 février 2022 23:07:05 GMT+01:00, "Maël REBOUX" ***@***.***> a écrit :

**Comment by yvecai** [comment]
Sorry, I can't reproduce in JOSM with today's extract, neither with an archive from yesterday (2022-02-06 13:00 UTC).
It's odd that you have the same offset in JOSM and QGIS, though.
