### ISSUE TITLE
displaying of piste:difficulty in relation

### ISSUE THREAD

**Issue by 5EOTlGWT** [yvecai/opensnowmap.org#38]
OSM-tag "piste:difficulty" isn't displaying in relation

**Comment by yvecai** [comment]
You're absolutely right, for nordic skiing Opensnowmap only displays difficulty tagged on ways.
I think it's worth it to map it on ways to mark the parts of a piste with particular difficulties for beginners.
Yves 

Le 3 avril 2022 12:38:19 GMT+02:00, 5EOTlGWT ***@***.***> a écrit :
